// Database schema, applied automatically on first use (see db.ts).
// Each migration runs once; bump by appending a new entry, never edit old ones.

export const MIGRATIONS: string[][] = [
  // 1: initial schema
  [
    `create table if not exists customers (
      id          integer generated by default as identity primary key,
      name        text not null,
      phone       text not null unique,
      address     text not null default '',
      created_at  timestamptz not null default now()
    )`,
    `create table if not exists products (
      id             integer generated by default as identity primary key,
      name           text not null,
      default_price  numeric(12,2) not null default 0,
      active         boolean not null default true,
      sizes          text[] not null default '{}',
      category       text not null default '',
      from_website   boolean not null default false,
      created_at     timestamptz not null default now()
    )`,
    `create unique index if not exists products_name_key on products (lower(name))`,
    `create table if not exists orders (
      id                integer generated by default as identity primary key,
      memo_no           integer generated by default as identity (start with 3849) unique not null,
      date              date not null default (now() at time zone 'Asia/Dhaka')::date,
      customer_id       integer references customers(id) on delete set null,
      customer_name     text not null default '',
      customer_phone    text not null default '',
      customer_address  text not null default '',
      courier           text not null default '',
      delivery_zone     text not null default '',
      delivery_charge   numeric(12,2) not null default 0,
      subtotal          numeric(12,2) not null default 0,
      cod_amount        numeric(12,2) not null default 0,
      payment_type      text not null default 'COD' check (payment_type in ('COD', 'Paid')),
      note              text not null default '',
      status            text not null default 'pending' check (status in ('pending', 'delivered', 'returned')),
      consignment_id    text,
      tracking_code     text,
      created_at        timestamptz not null default now()
    )`,
    `create index if not exists orders_date_idx on orders (date desc)`,
    `create index if not exists orders_customer_idx on orders (customer_id)`,
    `create table if not exists order_items (
      id            integer generated by default as identity primary key,
      order_id      integer not null references orders(id) on delete cascade,
      position      integer not null default 0,
      product_name  text not null,
      size          text not null default '',
      qty           integer not null default 1 check (qty > 0),
      unit_price    numeric(12,2) not null default 0,
      line_total    numeric(12,2) not null default 0
    )`,
    `create index if not exists order_items_order_idx on order_items (order_id)`,
    `create table if not exists settings (
      id    integer primary key default 1 check (id = 1),
      data  jsonb not null default '{}'
    )`,

    // next memo number without consuming it
    `create or replace function get_next_memo_no() returns integer language plpgsql as $$
    declare
      seq text := pg_get_serial_sequence('orders', 'memo_no');
      v_last bigint;
      v_called boolean;
    begin
      execute format('select last_value, is_called from %s', seq) into v_last, v_called;
      return case when v_called then v_last + 1 else v_last end;
    end $$`,

    `create or replace function set_next_memo_no(n integer) returns void language plpgsql as $$
    declare v_max integer;
    begin
      select coalesce(max(memo_no), 0) into v_max from orders;
      if n <= v_max then
        raise exception 'Next memo number must be greater than %', v_max;
      end if;
      perform setval(pg_get_serial_sequence('orders', 'memo_no'), n, false);
    end $$`,

    // create/update an order, its items and the customer in one transaction
    `create or replace function save_order(p jsonb) returns table (id integer, memo_no integer)
    language plpgsql as $$
    declare
      v_customer_id integer;
      v_order_id integer := nullif(p->>'id', '')::integer;
      v_memo integer;
    begin
      insert into customers as c (name, phone, address)
      values (p->>'customer_name', p->>'customer_phone', coalesce(p->>'customer_address', ''))
      on conflict (phone) do update set name = excluded.name, address = excluded.address
      returning c.id into v_customer_id;

      if v_order_id is null then
        insert into orders as o (date, customer_id, customer_name, customer_phone, customer_address,
          courier, delivery_zone, delivery_charge, subtotal, cod_amount, payment_type, note)
        values ((p->>'date')::date, v_customer_id, p->>'customer_name', p->>'customer_phone',
          coalesce(p->>'customer_address', ''), coalesce(p->>'courier', ''), coalesce(p->>'delivery_zone', ''),
          (p->>'delivery_charge')::numeric, (p->>'subtotal')::numeric, (p->>'cod_amount')::numeric,
          p->>'payment_type', coalesce(p->>'note', ''))
        returning o.id, o.memo_no into v_order_id, v_memo;
      else
        update orders as o set
          date = (p->>'date')::date,
          customer_id = v_customer_id,
          customer_name = p->>'customer_name',
          customer_phone = p->>'customer_phone',
          customer_address = coalesce(p->>'customer_address', ''),
          courier = coalesce(p->>'courier', ''),
          delivery_zone = coalesce(p->>'delivery_zone', ''),
          delivery_charge = (p->>'delivery_charge')::numeric,
          subtotal = (p->>'subtotal')::numeric,
          cod_amount = (p->>'cod_amount')::numeric,
          payment_type = p->>'payment_type',
          note = coalesce(p->>'note', '')
        where o.id = v_order_id
        returning o.memo_no into v_memo;
        if not found then
          raise exception 'Order not found';
        end if;
        delete from order_items where order_id = v_order_id;
      end if;

      insert into order_items (order_id, position, product_name, size, qty, unit_price, line_total)
      select v_order_id, x.ord::integer, x.v->>'product_name', coalesce(x.v->>'size', ''),
             (x.v->>'qty')::integer, (x.v->>'unit_price')::numeric, (x.v->>'line_total')::numeric
      from jsonb_array_elements(p->'items') with ordinality as x(v, ord);

      return query select v_order_id, v_memo;
    end $$`,

    // replace everything with a backup file's contents
    `create or replace function import_backup(p jsonb) returns void language plpgsql as $$
    begin
      truncate order_items, orders, customers, products restart identity cascade;

      insert into customers (id, name, phone, address, created_at)
      select distinct on (x.phone) x.id, x.name, x.phone, coalesce(x.address, ''),
             coalesce(nullif(x.created_at, '')::timestamptz, now())
      from jsonb_to_recordset(coalesce(p->'customers', '[]')) as x(id integer, name text, phone text, address text, created_at text)
      order by x.phone, x.id;

      insert into products (id, name, default_price, active, sizes, category, from_website)
      select x.id, x.name, coalesce(x.default_price, 0), coalesce(x.active, true), coalesce(x.sizes, '{}'),
             coalesce(x.category, ''), coalesce(x.from_website, false)
      from jsonb_to_recordset(coalesce(p->'products', '[]')) as x(id integer, name text, default_price numeric,
           active boolean, sizes text[], category text, from_website boolean)
      on conflict do nothing;

      insert into orders (id, memo_no, date, customer_id, customer_name, customer_phone, customer_address, courier,
        delivery_zone, delivery_charge, subtotal, cod_amount, payment_type, note, status, consignment_id,
        tracking_code, created_at)
      select x.id, x.memo_no, x.date::date, (select c.id from customers c where c.id = x.customer_id),
             coalesce(x.customer_name, ''), coalesce(x.customer_phone, ''), coalesce(x.customer_address, ''),
             coalesce(x.courier, ''), coalesce(x.delivery_zone, ''), coalesce(x.delivery_charge, 0),
             coalesce(x.subtotal, 0), coalesce(x.cod_amount, 0), coalesce(x.payment_type, 'COD'),
             coalesce(x.note, ''), coalesce(x.status, 'pending'), x.consignment_id, x.tracking_code,
             coalesce(nullif(x.created_at, '')::timestamptz, now())
      from jsonb_to_recordset(coalesce(p->'orders', '[]')) as x(id integer, memo_no integer, date text,
           customer_id integer, customer_name text, customer_phone text, customer_address text, courier text,
           delivery_zone text, delivery_charge numeric, subtotal numeric, cod_amount numeric, payment_type text,
           note text, status text, consignment_id text, tracking_code text, created_at text);

      insert into order_items (order_id, position, product_name, size, qty, unit_price, line_total)
      select (o.v->>'id')::integer, it.ord::integer, it.v->>'product_name', coalesce(it.v->>'size', ''),
             (it.v->>'qty')::integer, (it.v->>'unit_price')::numeric, (it.v->>'line_total')::numeric
      from jsonb_array_elements(coalesce(p->'orders', '[]')) as o(v),
           jsonb_array_elements(coalesce(o.v->'order_items', '[]')) with ordinality as it(v, ord);

      perform setval(pg_get_serial_sequence('customers', 'id'), coalesce((select max(id) from customers), 0) + 1, false);
      perform setval(pg_get_serial_sequence('products', 'id'), coalesce((select max(id) from products), 0) + 1, false);
      perform setval(pg_get_serial_sequence('orders', 'id'), coalesce((select max(id) from orders), 0) + 1, false);
      perform setval(pg_get_serial_sequence('order_items', 'id'), coalesce((select max(id) from order_items), 0) + 1, false);
      perform setval(pg_get_serial_sequence('orders', 'memo_no'),
        greatest(coalesce((select max(memo_no) from orders), 0) + 1, coalesce((p->>'next_memo_no')::integer, 1)), false);

      insert into settings (id, data) values (1, coalesce(p->'settings', '{}'))
      on conflict (id) do update set data = excluded.data;
    end $$`,
  ],
];
